FROM confluentinc/cp-kafka:7.3.2

WORKDIR /scripts

# Adding the initialization script
COPY init-kafka.sh /scripts/init-kafka.sh
RUN chmod +x /scripts/init-kafka.sh

# Keep container running during development for debugging purposes
CMD ["tail", "-f", "/dev/null"]